### ISSUE TITLE
Can't edit group details even when group is empty

### ISSUE THREAD

**Issue by lhoon** [doubtfire-lms/doubtfire-web#110]
System doesn;t allow a change in group details despite manually emptying the group and a few soft and hard refreshes.

<img width="1072" alt="screen shot 2018-07-12 at 10 56 36" src="https://user-images.githubusercontent.com/366554/42606697-646bfc74-85c2-11e8-9a60-97aa4b0702a1.png">

**Comment by macite** [comment]
Fixed with latest release!
