### ISSUE TITLE
Implement emoji and snippet picker.

### ISSUE THREAD

**Issue by jakerenzella** [doubtfire-lms/doubtfire-web#142]
When typing `:` in the comment box, an emoji picker should appear. So `:thumbsup:` would insert a 👍 .

We can then use this system to include snippets:

So `:indentation` can insert a paragraph about code formatting practices etc.

**Comment by gagolews** [comment]
This seems to have already been implemented?

**Comment by jakerenzella** [comment]
@gagolews Correct! Thanks
