### ISSUE TITLE
Recognised File types (Task list → Submission Details)

### ISSUE THREAD

**Issue by gagolews** [doubtfire-lms/doubtfire-web#252]
For SIT114, I will need the system to recognise the following file types:

Code: .R .Rmd .Rnw .Rhtml .Rpres .tex .md

Document: .html (it's a conflict, because html is recognised as Code now?)

**Comment by macite** [comment]
At the moment we can't do the HTML to document conversion - but this should be something the students can do. If you want the rendered version of the HTML then they can print this to PDF and upload the PDF. We could look at doing an extension to enable this, but need to think about how this works if the HTML has embedded resources.

If they upload it as code then it will create a PDF with syntaxes highlighted HTML.

**Comment by macite** [comment]
Syntax highlighting should work for any language supported by Pygments.

**Comment by macite** [comment]
Fixed

**Comment by gagolews** [comment]
Tried to upload an .Rmd file and got:

![image](https://user-images.githubusercontent.com/3193581/75776413-18316280-5da8-11ea-93ce-fcba1b64921e.png)

**Comment by macite** [comment]
Try clearing the browser cache - I'm guessing that it hasn't downloaded the new javascript code for the front end. I just ran a quick test and get this:

<img width="908" alt="image" src="https://user-images.githubusercontent.com/146138/75820090-db895980-5def-11ea-92de-d84b06aa1ee2.png">

**Comment by gagolews** [comment]
Yep, apologies, I'm a dumb user. 

All good!
