### ISSUE TITLE
trim whitespaces from fields imported from csv files

### ISSUE THREAD

**Issue by gagolews** [doubtfire-lms/doubtfire-web#253]
I didn't have time to double-check that but it seems that when I imported the csv file with task spec, the leading and trailing whitespaces in some of the fields were not trimmed - they should be

I could have a hand-made task list containing:

```
Task 1.2D,     1.2D,      Report Generation     ,1,2,false,5,false,80,[],"","[{""key"":""file0"",""name"":"".Rmd file"",""type"":""code""},{""key"":""file1"",""name"":"".html file"",""type"":""document""}]",1,Mon,11,Fri,11,Fri,Wrk01
```

**Comment by macite** [comment]
Done.
