### ISSUE TITLE
Student view: Not able to download submission

### ISSUE THREAD

**Issue by gagolews** [doubtfire-lms/doubtfire-web#254]
Once the submission a student  sends gets marked by a tutor and its status changes to *Complete*, there's a *Download Submission* button available in the *Submission* pane.

I though a student might want to view the submitted work while it's still being processed (*Ready For Feedback* status) -- just to make sure the artefact they sent is what they meant to share with us.

Currently it's not the case.

**Comment by macite** [comment]
This should be available - it may just need a few minutes to process the submission. This is done in a batch process at the moment, but will be more responsive in the future (we have a partial solution now - needs deployment and testing)

<img width="412" alt="image" src="https://user-images.githubusercontent.com/146138/75861113-06f06080-5e51-11ea-99ed-910d7a33d59f.png">
