### ISSUE TITLE
Open images sent in comments as dialog

### ISSUE THREAD

**Issue by AkshatBajaj** [doubtfire-lms/doubtfire-web#257]
At the moment, opening image comments throw this error.
![Capture](https://user-images.githubusercontent.com/32318980/76696609-741db480-66e1-11ea-8f2a-5482164103ad.PNG)

However, open image in new tab works fine.

**Comment by jakerenzella** [comment]
Fixed in: https://github.com/doubtfire-lms/doubtfire-web/pull/258
