### ISSUE TITLE
Querying Markdown Engine and Output From Comment Box Content

### ISSUE THREAD

**Issue by njsch** [doubtfire-lms/doubtfire-web#313]
Maybe this query is better suited for the API over the front-end.  and unfortunately I can't test out my concerns at this moment, as I am not enrolled in any units.  But I am wondering whether it might be a good idea to either fix, or if not fix, then at least highlight somewhere some of the potential limitation(s) of the markdown engine used to interpret the text typed into the assignment comment box.

One of the main issues I have noticed is that nested ordered and unordered lists are not always rendered properly.  They are if you use tabs but using single-space indentation seems unreliable (not sure if it makes any difference using different indentation levels of either two or four single spaces).

**Comment by jakerenzella** [comment]
Is the list issue the only issue you're having with markdown? We can probably tweak the settings of the markdown engine

**Comment by njsch** [comment]
@jakerenzella, it’s the only issue I know of so far.

**Comment by jakerenzella** [comment]
@njsch I know this has been a while, but there have been some recent changes to the markdown engine. If you are still using Doubtfire, could you please let me know if you're still experiencing these issues? Cheers

**Comment by njsch** [comment]
Can I paste the content in from a text editor, or should I type directly into the comment box? Just asking because apps such as Microsoft teams require you to type in the markdown directly as it is usually interpreted interactively.

**Comment by jakerenzella** [comment]
You can just paste it in 👍

**Comment by njsch** [comment]
@jakerenzella, It seems that some combinations of single-spaces work with ordered lists but don't cope with unordered ones.  Anyway, it doesn't matter as double-space indents and four spaces seem to work more consistently as well as tabs now.

This is the markdown I used for testing:

```# Lists separated with cr/lf:
## Asterisks:
* Unordered list
	* With tabs using asterisks
		* Another level

* unordered list
 * With single-space indent and asterisks
  * Another level

* Unordered list
  * With two spaces and asterisks
    * Another level

* Unordered list
   * With three spaces and asterisks
      * Another level

* Unordered list
    * With four spaces and asterisks
        * Another level

## With dashes:
- Unordered list
	- With tabs using dashes
		- Another level

- unordered list
 - With single-space indent and dashes
  - Another level

- Unordered list
  - With two spaces and dashes
    - Another level

- Unordered list
   - With three spaces and dashes
      - Another level

- Unordered list
    - With four spaces and dashes
        - Another level

Single-space indent:
* a list nested with 
  1. ordered
  2. ordered
    * unordered again

Double-space indent:
* a list nested with 
 1. ordered
 2. ordered
  * unordered again

Single-space indent:
1. Ordered
 1. Ordered
  * Unordered
2. Ordered

Double-space indent:
1. Ordered
  1. Ordered
    * Unordered
2. Ordered

Tabulated:
* a list nested with 
	1. ordered
	2. ordered
		* unordered again

1. Ordered
	1. Ordered
		* Unordered
2. Ordered
```

**Comment by jakerenzella** [comment]
Thanks @njsch we soils be adhering to the GitHub markdown format so I'm now closing this issue.

**Comment by njsch** [comment]
![Screenshot1](https://user-images.githubusercontent.com/56899272/121892049-97f5fd00-cd5f-11eb-9c9f-7b446ffbab81.png)
![Screenshot2](https://user-images.githubusercontent.com/56899272/121892053-99272a00-cd5f-11eb-9a83-7b0e8d6dd3ef.png)
![Screenshot3](https://user-images.githubusercontent.com/56899272/121892055-99272a00-cd5f-11eb-9fc6-7f8dc24b1ef2.png)

**Comment by jakerenzella** [comment]
@njsch  thanks for your help on this, that is actually a very helpful image! 

I'm trying be more active on issues so please feel free to let me know if there's any more issues.

**Comment by njsch** [comment]
@jakerenzella Well, you can thank Cristal Gutierrez of Aira Tech Corp. for those images.

Will do RE any other issues.
