### ISSUE TITLE
Task Description Card - Cannot download resources

### ISSUE THREAD

**Issue by erickao5858** [doubtfire-lms/doubtfire-web#326]
![image](https://user-images.githubusercontent.com/31674374/102002445-a895ce00-3d50-11eb-94a7-0003ab56d90b.png)
The resource download function doesn't work.
@macite

**Comment by erickao5858** [comment]
Possible reason: missing task-def-id
![image](https://user-images.githubusercontent.com/31674374/102002562-c879c180-3d51-11eb-9f3b-1828503ad0ce.png)
![image](https://user-images.githubusercontent.com/31674374/102002567-cb74b200-3d51-11eb-973b-8a2b0f494bc9.png)

**Comment by erickao5858** [comment]
Temporary solution: 
Get task_def_id from another component
![image](https://user-images.githubusercontent.com/31674374/102002614-4c33ae00-3d52-11eb-9d4e-2e9def4221f9.png)
It is 3879.
Using 3879 replacing the undefined get parameter

**Comment by macite** [comment]
Fixed and deployed - reload then it should work. See e943c8d2ab9caad9cf26d309a2017c929e5df826
