### ISSUE TITLE
Unable to Categorically Set Relevance of ULOs to 0

### ISSUE THREAD

**Issue by njsch** [doubtfire-lms/doubtfire-web#341]
Currently, OnTrack prevents you from submitting / uploading assignments if you set all of the ULO relevancy values to 0 - to rationally declare them all as irrelevant.  Normally this does not matter but sometimes it does matter in situations where, for example, an academic may set a task at the beginning of a learning period where you have to submit a 0-credit level assessment in order to practice using Doubtfire.  Could someone change this?

**Comment by jakerenzella** [comment]
I believe the idea here is that 0 is regarded as not filled out, with 1 being the lowest alignment.

In this situation, assigning an alignment of 1 would be appropriate, as it is the least aligned. Also, I would expect that a task like you have described would not be included in the portfolio itself (as it is just an introductory task), so this is likely not that important overall.

Thanks,

Jake
