### ISSUE TITLE
Feature request: Order by task inbox by task ID/name

### ISSUE THREAD

**Issue by gagolews** [doubtfire-lms/doubtfire-web#367]
I guess tasks in the Task Inbox are now ordered by submission date, the option to order by task ID would make my life easier.

![image](https://user-images.githubusercontent.com/3193581/120404816-86d5e500-c38a-11eb-9e5c-73947ae129c8.png)

**Comment by jakerenzella** [comment]
Hi @gagolews, You can sort of do this now by selecting the task definition in the first dropdown, and then switching it as you finish marking each task - it's not a sort but it is mostly what you're looking for. In the future we can investigate this as a feature request. Cheers

**Comment by gagolews** [comment]
Yeah, nah, but with 15 different task types which are submitted in a highly non-unpredictable order it is a bit of a struggle... :)

**Comment by jakerenzella** [comment]
Hey @gagolews, is it possible you misunderstood my suggestion? I was referring to using the filter to filter the task definition (not the individual tasks). This will filter your inbox to only display each submission filtered by each of your 15 or so task definitions. Then you can mark and provide feedback down the inbox one task-type at a time. See the screenshot attached:
![df-filter](https://user-images.githubusercontent.com/5138218/121308914-ef056780-c944-11eb-854e-427b441e4712.jpg)

Hope this helps, and I'll take the feature suggestion for sorting on-board.

Cheers,

Jake

**Comment by gagolews** [comment]
I know about this, but this is not very convenient throughout the trimester, when I run mini-marking sessions 3 times/week, where there can be 4 submissions of task 7, 1 submission of task 9, 2 submissions of task 11, and 3 submissions of task 14, with all the other tasks not present at all. - they all appear in random order (or rather, sorted by submission date).

It's merely a feature request, that could make my life easier next year.

**Comment by gagolews** [comment]
Actually something for the capstone students to implement maybe. :)

**Comment by jakerenzella** [comment]
Thanks, I'll document this -- I agree, would be good for a capstone deliverable.

**Comment by jakerenzella** [comment]
@gagolews This is merged and will be available at the next deployment at Deakin 👍

**Comment by gagolews** [comment]
Splendid 🙂

**Comment by jakerenzella** [comment]
@gagolews Hopefully you've had a chance to try this new feature out -- let me know how that experience has been.

**Comment by gagolews** [comment]
I don't have any ontrack-based units this trimester, so.... ;)
