### ISSUE TITLE
Status reverts after confirming upload

### ISSUE THREAD

**Issue by kr3nshaw** [doubtfire-lms/doubtfire-web#37]
https://www.dropbox.com/s/6r1taiuim1kmfbc/Doubtfire.mov?dl=0

**Comment by macite** [comment]
Can you reproduce this reliably? Under what conditions does this occur?

**Comment by kr3nshaw** [comment]
Not reliably, but it only seems to occur when there are a large number of files being uploaded (around 5 or more).

**Comment by macite** [comment]
Should be sorted now.
