### ISSUE TITLE
Staff inbox tasks disappear under certain circumstances -- reappear on any change to the UI

### ISSUE THREAD

**Issue by macite** [doubtfire-lms/doubtfire-web#372]
Easiest way to see is to open the "Search Inbox". The tasks then disappear, but will reappear on a change in window size or closing the "Search Inbox". Similarly, Mark by Definition has the same issue if you change the task filter.

**Comment by jakerenzella** [comment]
This seems related to https://github.com/angular/components/issues/10117 which is actively being worked on

**Comment by jakerenzella** [comment]
This issue was resolved by the Angular team
