### ISSUE TITLE
Task name is too large for the label

### ISSUE THREAD

**Issue by kr3nshaw** [doubtfire-lms/doubtfire-web#38]
<img width="69" alt="doubtfire" src="https://cloud.githubusercontent.com/assets/20672068/17686024/514b7442-63ac-11e6-845f-7e1067963920.png">

**Comment by alexcu** [comment]
Hi @kr3nshaw a bit late reply but would you be able to provide more context where this label is being used? Doubtfire v5 has been entirely redesigned and therefore this issue may no longer be applicable. Cheers!

**Comment by kr3nshaw** [comment]
The label is on the **Task List**, on the **Progress** tab.

**Comment by alexcu** [comment]
I see... this has since been removed in the redesign, so is no longer applicable.
