### ISSUE TITLE
Doubtfire does not handle international timezones very well

### ISSUE THREAD

**Issue by ublefo** [doubtfire-lms/doubtfire-web#408]
Doubtfire currently has some issues handling timezones correctly. International students in different time zones (especially the ones behind AEST) will see conflicting information about due dates displayed on Doubtfire. The due date just below "Aim To Complete Soon" tracks system TZ, but the due date in the Task Details section below does not, so Doubtfire is displaying two conflicting dates. 

When a deadline is approaching and there is less than one day left, the hour display is also incorrect. If a student is in Los Angeles, the display will be **17 hours** off. So while the student still thinks they have time to submit, by the time they have submitted the task, the tutor will probably see a time exceeded status on their end and might choose not to provide feedback (assuming the tutors are in AEST).

How to reproduce: 
Setting the system time zone to a time zone significantly behind AEST (such as Pacific) and launch the browser, or run something like `TZ="America/Los_Angeles" chromium-browser` on Linux and potentially macOS.

![image](https://user-images.githubusercontent.com/90136978/132127562-b557241e-977c-48a6-a7e5-5c31183677cf.png)

Here are a few suggestions:
1. A simple fix which should be applied asap is to hard-code everything to track AEST and unify the two fields.
2. A better long-term solution is to allow the user to select time zone offsets, like D2L would:

![image](https://user-images.githubusercontent.com/90136978/132128065-65a1f8b9-614b-4dc5-9bf2-0c0ab54a0ca2.png)

**Comment by jakerenzella** [comment]
Hi @ublefo,

I agree the conflicting dates being different here are confusing, however, students shouldn't actually be impacted by this as we calculate due dates using the anywhere on earth timezone. So the student in Los Angelos in your example would in fact have had slightly more than 17 hours remaining.

You are right that the first date presented is using the local due date, but the second may be using the alternative date format only if you're viewing the task in the task definition panel (so not on a student's page).

@macite Does this all ring true to you? Should we consolidate these two fields?

**Comment by macite** [comment]
We need to look into this - they should be consistent. The server should be returning the "day" it is due. It looks like one of these must be using a time rather than date value... or incorrectly mapping this with the timezone.

**Comment by jakerenzella** [comment]
Should we be displaying the local time, or the AOE time? If we decide I should be able to fix this quite easily

**Comment by macite** [comment]
It should be the day specified. They are due "Wednesday 8th September" for example. So everywhere should show "Wed 8th".

**Comment by macite** [comment]
So no time - just the day.

**Comment by jakerenzella** [comment]
My bet is in this example it should have been the 9th, but the first date is incorrectly showing the local time. I'll look into this.

**Comment by ublefo** [comment]
Thanks for looking into this, I don't have any further opinions on this other than the two fields should be consistent. However you handle time zones outside of AEST is your call.

**Comment by macite** [comment]
I think we have solved this issue now - times should be consistent across the different pages now. In all cases, it should show the indicated "Day" regardless of the timezone.
