### ISSUE TITLE
Conflicting due date text description and actual due date handling

### ISSUE THREAD

**Issue by ublefo** [doubtfire-lms/doubtfire-web#409]
Currently Doubtfire uses "Aim to start this task *by*" and "Aim to complete *by*" to specify start and due dates, which implies it's inclusive. However, at least the "Aim to complete *by*" date is actually exclusive, as the task will show up as "time exceeded" if the student still have not submitted anything *before* the specified date.

One of the following fixes should be applied:
- Change the wording to *before*
- Change the date handling logic to inclusive

Please refer to the following page for more details about "before" and "by" when it comes to specifying dates:
https://english.stackexchange.com/questions/106167/before-date-versus-by-date

**Comment by sekaiwish** [comment]
After coming to this same conclusion, I think the correct solution to this issue would be to implement the inclusive date logic. Implementing _before_ wording would only be a bandaid solution.

**Comment by njsch** [comment]
@jakerenzella, @macite, not sure if this is exactly the same but seems similar to my issue as per relevant emails.

**Comment by macite** [comment]
I think this is fixed now that we have corrected timezone issues. Looking at the back end the actually submission time is checked against AoE timezone at day / month / year 23:59:59... so end of the day anywhere on earth. Front end gets the date and now renders it correctly.
