### ISSUE TITLE
Graph using incorrect values.

### ISSUE THREAD

**Issue by naturalredhead** [doubtfire-lms/doubtfire-web#41]
The graphs shown are for someone who has submitted all work, therefore To Submit should be at zero, with To Complete at 18%

The graphs show both To Submit and To Complete at 27%

![image](https://cloud.githubusercontent.com/assets/23257049/20001044/79d0f304-a2ce-11e6-9f66-ddbf1ccb251c.png)
![image](https://cloud.githubusercontent.com/assets/23257049/20001058/9090a382-a2ce-11e6-9d80-bc3f5dc22f3f.png)

**Comment by macite** [comment]
What does the task status look like?

**Comment by macite** [comment]
The graph does not update past the end date of the unit, so this is most likely the issue you are seeing. Contact your unit convenor and ask them to extend the end date.

**Comment by naturalredhead** [comment]
As requested - task list

![image](https://cloud.githubusercontent.com/assets/23257049/20027654/6eeaaa62-a36d-11e6-9e8a-088ea28611c0.png)

This issue is not about the end date of the unit, it has been happening all semester - the To Submit Line has had the same values as the To Complete line.

**Comment by macite** [comment]
Once a tasks are marked as complete the two lines should be the same. If your three tasks were submitted after the end date if the unit they won't show in the chart. Changing the end date should fix this.

**Comment by naturalredhead** [comment]
Two of the tasks were submitted a week before the end date, and one on the end date, but prior to the end of the day, and the whole time, indeed the whole semester the graph showed just the pink line as per the first screenshot. Given they were submitted, and not completed, I would expect the blue line to be visible with a drop to zero and the pink line to still be higher.
