### ISSUE TITLE
Notifications for task changes seem broken

### ISSUE THREAD

**Issue by ublefo** [doubtfire-lms/doubtfire-web#479]
I've noticed some issues with the notification feature in doubtfire. 

First of all, the site does not prompt the user for permission to send push notifications at all, I have tried this in Firefox and Chromium, with cleared cache/cookies, and I've tried toggling the notification settings as well, none of which could make the permission prompt appear. Websites such as MS Teams would use a small popup on the page asking whether the user wishes to opt-in, and tries to send a test notification to ensure the permission is set up correctly. Given there is a persistent preference associated with each user's account, I think the site should test for notification permission and try to get the user to grant it again on page load if cookies has been cleared, and the user has enabled notifications in their account.

Second, there seems to be a lack of Web Push support (if it had any I was not able to make it work), which is problematic given the users can't be expected to keep the page open in their browsers all the time. Most modern browsers ship with their own built-in remote push server already configured, and imo this should be implemented in doubtfire since currently there is absolutely no way for the user to receive notifications when a status of their task has changed or a feedback has been posted. Doubtfire currently has no email notification support and no RSS feeds, and I think there should be at least _one_ method to notify the users without them having to log into a browser.

**Comment by TinyServal** [comment]
Okay, I looked into this and the notification switch in doubtfire settings is _not_ for task changes, it's for those weekly digest emails. Actual task change notification is not a feature that has been implemented.

**Comment by TinyServal** [comment]
Closing as this isn't really a frontend issue, moving to the API repo.
