### ISSUE TITLE
Mysterious numeric value in the burndown chart

### ISSUE THREAD

**Issue by macite** [doubtfire-lms/doubtfire-web#486]
![imgpsh_mobile_save](https://user-images.githubusercontent.com/146138/157774504-1bec222c-4338-45c2-a2cd-ff150c907f89.jpg)

This should not appear. While this component needs to be updated at some stage, it would be good to create a quick patch to remove it for now.

**Comment by jakerenzella** [comment]
Odd - I'll look into this

**Comment by macite** [comment]
No need @jakerenzella - we have it under control :)

**Comment by macite** [comment]
No need @jakerenzella - we have it under control :)

**Comment by isdampe** [comment]
1647820800 is UTC March 21 2022 00:00:00 in epoch time so I'm guessing that is correlating with the underlying timestamps of the labels on the X-axis.

**Comment by macite** [comment]
Issues is resolved.
