### ISSUE TITLE
Task editor stream and groupset are in the wrong locations

### ISSUE THREAD

**Issue by macite** [doubtfire-lms/doubtfire-web#492]
<img width="891" alt="Pasted_Image_17_3_2022__10_03_pm" src="https://user-images.githubusercontent.com/146138/158795991-20a4b42e-d1b9-45c0-a3c1-f8ad7aa6ea84.png">

When a unit has group tasks, the task editor columns headers and data do not align.

**Comment by RayGuo-ergou** [comment]
PR #493 created to resolved this issue.
