### ISSUE TITLE
Task viewer no longer fits on screen in Chrome Canary

### ISSUE THREAD

**Issue by SinZ163** [doubtfire-lms/doubtfire-web#64]
![](http://i.imgur.com/troXcvp.png)

`<div class="task-viewer-toolbar clearfix">`

Does not happen when `display: flex;` is disabled ![](http://i.imgur.com/2coeeX3.png)

**EDIT:**  
Chrome Canary version 59.0.3032.0 (Official Build) canary (64-bit)

**Comment by alexcu** [comment]
Hey @SinZ163, this issue seems to be for Doubtfire v4, which has been deprecated and will no longer be maintained. Doubtfire v5 has been entirely redesigned and most of this content has/will be removed 😊. Cheers!
