### ISSUE TITLE
"Assessment Information" is retained if I transfer to task with no assessment information.

### ISSUE THREAD

**Issue by mjocen** [doubtfire-lms/doubtfire-web#82]
Conditions:
- Student view
- Not Started tasks

Issue:
Selected task with "Assessment Information" box and then transferring to a different task retains the "Assessment Information" box.

Review:
If done the other way around, "Assessment Information" box is not shown.

Procedure:
[For issue]
Student Home View -> Project 2 task -> Working with Enumerations
<img width="960" alt="issue1_part1" src="https://user-images.githubusercontent.com/30681814/28906893-355ec564-785e-11e7-8381-78f1655f1be9.PNG">

<img width="960" alt="issue1_part2" src="https://user-images.githubusercontent.com/30681814/28906983-01100222-785f-11e7-9f49-330083d1ca75.PNG">

<img width="959" alt="issue1_part3" src="https://user-images.githubusercontent.com/30681814/28906991-0e7ccac6-785f-11e7-984c-caad25e29826.PNG">

[issue after review]
Student Home View -> Working with Enumerations -> Project 2 task

<img width="960" alt="issue1_part1" src="https://user-images.githubusercontent.com/30681814/28907031-435258e2-785f-11e7-8380-7acd01a1c7fd.PNG">

<img width="960" alt="issue1_part4" src="https://user-images.githubusercontent.com/30681814/28907033-4824b978-785f-11e7-9848-5b842141a540.PNG">

<img width="960" alt="issue1_part5" src="https://user-images.githubusercontent.com/30681814/28907036-4c4eb328-785f-11e7-8ae9-b663bd6c474d.PNG">

**Comment by macite** [comment]
Hi @mjocen 

I've tried to replicate without success. Can you let me know what browser you are using and if there are any errors on the Javascript Console when this happens for you?

cheers,
Andrew

**Comment by mjocen** [comment]
Hi @macite 

I'm using Google Chrome version 60.0.3112.90 in Windows.
I also tried in Mozilla Firefox version 45.3 in T105 lab computer and similar issue occurs.
For both, I'm not sure how to detect the Javascript error but nothing came out when I opened the JS Console and proceeded with the issue.

Regards,
Jocen

**Comment by macite** [comment]
Got it now :)

**Comment by macite** [comment]
Fixed in commit 0865438
