### ISSUE TITLE
Task Comment Viewer - No Text Wrapping In Firefox

### ISSUE THREAD

**Issue by MattVZDeakin** [doubtfire-lms/doubtfire-web#93]
When using Firefox, content of the "Task Comment Viewer" element does not wrap:

![screenshot from 2018-04-06 12-29-37](https://user-images.githubusercontent.com/33710878/38400968-3b9b5f10-3996-11e8-8841-5ead1f85f303.png)

Bug most likely occurs within the "task-comments-viewer.scss" file.

**Comment by jakerenzella** [comment]
<img width="366" alt="screen shot 2018-07-05 at 9 09 57 pm" src="https://user-images.githubusercontent.com/5138218/42320181-cb50ceea-8097-11e8-9fa5-0875982ddea9.png">

Fixed as of #100
