### ISSUE TITLE
Task Comment Viewer - Comment Delete Button Visible To All Users

### ISSUE THREAD

**Issue by MattVZDeakin** [doubtfire-lms/doubtfire-web#94]
The delete button for a comment is visible to all users even if they did not author the comment.
![screenshot from 2018-04-06 13-35-58](https://user-images.githubusercontent.com/33710878/38402424-7eab5df6-399f-11e8-9b97-fae055ddda6c.png)

This should be changed so that the delete button is only visible if the user is the author of the comment.

**Comment by jakerenzella** [comment]
@MattVZDeakin Do you still see this behavior?
